### DISCUSSION TITLE
Do we have any support for Optimization?

### DISCUSSION THREAD

**Discussion by Anupam2528** [javers/javers#1321] [Q&A]
Hi Team,
First of all Thank you so much for the tremendous library for auditing in a Java.  
I am using Javers in my spring-boot application for a Auditing purpose and it is giving me the good results.
However I am facing the issue with performance.
I have a POST request which saves the multiple entities in a database. 
My POST request is taking around **5 seconds** to respond and when I disabled the Javers it is taking **less than 1 second**. (When I am saying disable I mean I commented the @JaversSpringDataAuditable annotation on the all entities.)
I am using PostgreSQL database.

Below is the configuration which I am using : 
```
javers:
  sqlSchema: sample_schema
  algorithm: LEVENSHTEIN_DISTANCE
  newObjectSnapshot: true
  initialChange: true
```

Do we have any configurations that can optimize the performance of the application? 

I used JProfiler for performance monitoring and observed that almost all entities are taking around **900-1000 ms** for the save or saveAll methods in a JPA.

Please let me know if we have anything to improve the performance with Javers.
