### ISSUE TITLE
javers creates extra commit with state UPDATE when deleteById method called on repository

### ISSUE THREAD

**Issue by sltet** [javers/javers#1122]
**Clear description of my expectations versus reality**

When calling the method `deleteById` on a mongorepository after calling the `save` method, i'm getting two objects created in the database. One with the terminal state and another one with an update state

Spring repository:
```java
@Repository
@JaversSpringDataAuditable
public interface WorkPlanRepository extends MongoRepository<WorkPlan, String>,
    WorkPlanRepositoryExtended {

  @Override
  @JaversAuditableDelete(entity = WorkPlan.class)
  void deleteById(String s);
}
```

Mongo database state after calling the deleteById method:

![Screen Shot 2021-07-13 at 10 40 58 PM](https://user-images.githubusercontent.com/6503472/125552326-467c7c7b-f992-45d4-83b3-61c8dc6d9200.png)

Now when i'm calling the `javers.findChanges()` method this i what i get:

```java
QueryBuilder jqlQuery = QueryBuilder.byInstanceId(new ObjectId(entityId), typeParameterClass).limit(size).skip(offset);
jqlQuery = jqlQuery.withChildValueObjects(true).withScopeCommitDeep();
jqlQuery = dateRangeQueryDecorator(from, to, jqlQuery);
System.out.println(javers.findChanges(jqlQuery.build()).devPrint());
```

### Result:
`
commit 765.00 
* changes on WorkPlan/1626227942,4105681,12657625,8618 :
  - InitialValueChange{ property: 'id', left:'',  right:'60ee44e6c123d921aa3ea5d1' } 
  - InitialValueChange{ property: 'companyId', left:'',  right:'5d18e50a41597cb298fd3d15' } 
  - InitialValueChange{ property: 'description', left:'',  right:'simple day 5d18e50a41597cb298fd3d15' } 
  - InitialValueChange{ property: 'startDate', left:'',  right:'01 Jan 2021' } 
  - InitialValueChange{ property: 'endDate', left:'',  right:'31 Dec 2021' } 
  - InitialValueChange{ property: 'expiryDate', left:'',  right:'31 Dec 2023' } 
  - InitialValueChange{ property: 'rotation', left:'',  right:'1' } 
  - InitialValueChange{ property: 'weeklyTargetHours', left:'',  right:'1' } 
  - InitialValueChange{ property: 'rotationDaysInterval', left:'',  right:'1' } 

commit 764.01 
* changes on WorkPlan/1626227942,4105681,12657625,8618 :
  - ObjectRemoved{ object removed: WorkPlan/1626227942,4105681,12657625,8618 } 
  - TerminalValueChange{ property: 'id', left:'60ee44e6c123d921aa3ea5d1',  right:'' } 
  - TerminalValueChange{ property: 'companyId', left:'5d18e50a41597cb298fd3d15',  right:'' } 
  - TerminalValueChange{ property: 'description', left:'simple day 5d18e50a41597cb298fd3d15',  right:'' } 
  - TerminalValueChange{ property: 'startDate', left:'01 Jan 2021',  right:'' } 
  - TerminalValueChange{ property: 'endDate', left:'31 Dec 2021',  right:'' } 
  - TerminalValueChange{ property: 'expiryDate', left:'31 Dec 2023',  right:'' } 
  - TerminalValueChange{ property: 'rotation', left:'1',  right:'' } 
  - TerminalValueChange{ property: 'weeklyTargetHours', left:'1',  right:'' } 
  - TerminalValueChange{ property: 'rotationDaysInterval', left:'1',  right:'' } 

commit 763.00 
* changes on WorkPlan/1626227942,4105681,12657625,8618 :
  - NewObject{ new object: WorkPlan/1626227942,4105681,12657625,8618 } 
  - InitialValueChange{ property: 'id', left:'',  right:'60ee44e6c123d921aa3ea5d1' } 
  - InitialValueChange{ property: 'companyId', left:'',  right:'5d18e50a41597cb298fd3d15' } 
  - InitialValueChange{ property: 'description', left:'',  right:'simple day 5d18e50a41597cb298fd3d15' } 
  - InitialValueChange{ property: 'startDate', left:'',  right:'01 Jan 2021' } 
  - InitialValueChange{ property: 'endDate', left:'',  right:'31 Dec 2021' } 
  - InitialValueChange{ property: 'expiryDate', left:'',  right:'31 Dec 2023' } 
  - InitialValueChange{ property: 'rotation', left:'',  right:'1' } 
  - InitialValueChange{ property: 'weeklyTargetHours', left:'',  right:'1' } 
  - InitialValueChange{ property: 'rotationDaysInterval', left:'',  right:'1' }
`

How can i get rid of the extra commit ( commit 765.00 ) generated after the terminal state ? When calling `javers.findChanges()` i expect to have only commits for `NewObject` and `ObjectRemoved` and not the extra one.

**Javers' Version**
6.2.3

** Javers' Configuration**
```yaml
javers:
  mappingStyle: FIELD
  algorithm: SIMPLE
  commitIdGenerator: synchronized_sequence
  prettyPrint: true
  typeSafeValues: false
  initialChanges: true
  terminalChanges: true
  newObjectSnapshot: true # deprecated
  auditableAspectEnabled: true
  springDataAuditableRepositoryAspectEnabled: true
  documentDbCompatibilityEnabled: false
  objectAccessHook: org.javers.spring.mongodb.DBRefUnproxyObjectAccessHook
  snapshotsCacheSize: 0
  prettyPrintDateFormats:
    localDateTime: "dd MMM yyyy, HH:mm:ss"
    zonedDateTime: "dd MMM yyyy, HH:mm:ssZ"
    localDate: "dd MMM yyyy"
    localTime: "HH:mm:ss"
```
