### ISSUE TITLE
Auto Configuration missing ObjectAccessHook parameter (yml)

### ISSUE THREAD

**Issue by duayres** [javers/javers#708]
On doc there is a clear explanation about the javers core auto configuration (Spring framework integration):
"Each property in the Spring application.yml file has the corresponding with*() method in the JaversBuilder."
I've tried to write the method without the "with" in snake case on my yaml as follows:
``` 
javers:
    ...
    objectAccessHook: my.package.CustomHibernateUnproxy
```
But it did not work, it seems missing.

Javers version: 3.11.

----
Edit: Maybe a subsection to denote the transactional builder and then the parameter can be implemented:
```
javers:
    ...
    transactional:
        objectAccessHook: my.package.CustomHibernateUnproxy
```
